COMMON_ENTITIES = [
    # --- INDIAN BLUECHIPS & NIFTY 100 (100 companies) ---
    ("reliance", "Reliance Industries Limited", "RELIANCE.NS", "Energy", "Oil & Gas Refining & Marketing"),
    ("tcs", "Tata Consultancy Services Limited", "TCS.NS", "Technology", "Information Technology Services"),
    ("infosys", "Infosys Limited", "INFY.NS", "Technology", "Information Technology Services"),
    ("hdfc bank", "HDFC Bank Limited", "HDFCBANK.NS", "Financial Services", "Private Sector Bank"),
    ("icici bank", "ICICI Bank Limited", "ICICIBANK.NS", "Financial Services", "Private Sector Bank"),
    ("sbi", "State Bank of India", "SBIN.NS", "Financial Services", "Public Sector Bank"),
    ("state bank of india", "State Bank of India", "SBIN.NS", "Financial Services", "Public Sector Bank"),
    ("bharti airtel", "Bharti Airtel Limited", "BHARTIARTL.NS", "Communication Services", "Telecom Services"),
    ("airtel", "Bharti Airtel Limited", "BHARTIARTL.NS", "Communication Services", "Telecom Services"),
    ("lic", "Life Insurance Corporation of India", "LICI.NS", "Financial Services", "Insurance"),
    ("itc", "ITC Limited", "ITC.NS", "Consumer Defensive", "Tobacco"),
    ("l&t", "Larsen & Toubro Limited", "LT.NS", "Industrials", "Engineering & Construction"),
    ("larsen & toubro", "Larsen & Toubro Limited", "LT.NS", "Industrials", "Engineering & Construction"),
    ("hul", "Hindustan Unilever Limited", "HINDUNILVR.NS", "Consumer Defensive", "Household & Personal Products"),
    ("hindustan unilever", "Hindustan Unilever Limited", "HINDUNILVR.NS", "Consumer Defensive", "Household & Personal Products"),
    ("bajaj finance", "Bajaj Finance Limited", "BAJFINANCE.NS", "Financial Services", "Non-Banking Financial Company"),
    ("hcl tech", "HCL Technologies Limited", "HCLTECH.NS", "Technology", "Information Technology Services"),
    ("maruti", "Maruti Suzuki India Limited", "MARUTI.NS", "Consumer Cyclical", "Auto Manufacturers"),
    ("maruti suzuki", "Maruti Suzuki India Limited", "MARUTI.NS", "Consumer Cyclical", "Auto Manufacturers"),
    ("sun pharma", "Sun Pharmaceutical Industries Limited", "SUNPHARMA.NS", "Healthcare", "Drug Manufacturers—Specialty & Generic"),
    ("adani enterprises", "Adani Enterprises Limited", "ADANIENT.NS", "Industrials", "Conglomerates"),
    ("adani Green", "Adani Green Energy Limited", "ADANIGREEN.NS", "Utilities", "Utilities—Renewable"),
    ("adani ports", "Adani Ports and Special Economic Zone Limited", "ADANIPORTS.NS", "Industrials", "Marine Ports"),
    ("tata motors", "Tata Motors Limited", "TATAMOTORS.NS", "Consumer Cyclical", "Auto Manufacturers"),
    ("ongc", "Oil and Natural Gas Corporation Limited", "ONGC.NS", "Energy", "Oil & Gas Exploration & Production"),
    ("ntpc", "NTPC Limited", "NTPC.NS", "Utilities", "Utilities—Independent Power Producers"),
    ("axis bank", "Axis Bank Limited", "AXISBANK.NS", "Financial Services", "Private Sector Bank"),
    ("kotak bank", "Kotak Mahindra Bank Limited", "KOTAKBANK.NS", "Financial Services", "Private Sector Bank"),
    ("kotak mahindra", "Kotak Mahindra Bank Limited", "KOTAKBANK.NS", "Financial Services", "Private Sector Bank"),
    ("coal india", "Coal India Limited", "COALINDIA.NS", "Energy", "Coal Mining"),
    ("titan", "Titan Company Limited", "TITAN.NS", "Consumer Cyclical", "Luxury Goods"),
    ("ultratech", "UltraTech Cement Limited", "ULTRACEMCO.NS", "Basic Materials", "Building Materials"),
    ("jsw steel", "JSW Steel Limited", "JSWSTEEL.NS", "Basic Materials", "Steel"),
    ("power grid", "Power Grid Corporation of India Limited", "POWERGRID.NS", "Utilities", "Utilities—Regulated Electric"),
    ("nestle", "Nestle India Limited", "NESTLEIND.NS", "Consumer Defensive", "Packaged Foods"),
    ("asian paints", "Asian Paints Limited", "ASIANPAINT.NS", "Basic Materials", "Chemicals"),
    ("hindalco", "Hindalco Industries Limited", "HINDALCO.NS", "Basic Materials", "Aluminum"),
    ("grasim", "Grasim Industries Limited", "GRASIM.NS", "Industrials", "Conglomerates"),
    ("bajaj finserv", "Bajaj Finserv Limited", "BAJAJFINSV.NS", "Financial Services", "Financial Services"),
    ("indusind bank", "IndusInd Bank Limited", "INDUSINDBK.NS", "Financial Services", "Private Sector Bank"),
    ("tata steel", "Tata Steel Limited", "TATASTEEL.NS", "Basic Materials", "Steel"),
    ("ltimindtree", "LTIMindtree Limited", "LTIM.NS", "Technology", "Information Technology Services"),
    ("tech mahindra", "Tech Mahindra Limited", "TECHM.NS", "Technology", "Information Technology Services"),
    ("cipla", "Cipla Limited", "CIPLA.NS", "Healthcare", "Drug Manufacturers—Specialty & Generic"),
    ("dr reddy", "Dr. Reddy's Laboratories Limited", "REDDY.NS", "Healthcare", "Drug Manufacturers—Specialty & Generic"),
    ("britannia", "Britannia Industries Limited", "BRITANNIA.NS", "Consumer Defensive", "Packaged Foods"),
    ("apollo hospitals", "Apollo Hospitals Enterprise Limited", "APOLLOHOSP.NS", "Healthcare", "Medical Care Facilities"),
    ("mahindra & mahindra", "Mahindra & Mahindra Limited", "M&M.NS", "Consumer Cyclical", "Auto Manufacturers"),
    ("m&m", "Mahindra & Mahindra Limited", "M&M.NS", "Consumer Cyclical", "Auto Manufacturers"),
    ("shriram finance", "Shriram Finance Limited", "SHRIRAMFIN.NS", "Financial Services", "Non-Banking Financial Company"),
    ("hero motocorp", "Hero MotoCorp Limited", "HEROMOTOCO.NS", "Consumer Cyclical", "Auto Manufacturers"),
    ("eicher motors", "Eicher Motors Limited", "EICHERMOT.NS", "Consumer Cyclical", "Auto Manufacturers"),
    ("wipro", "Wipro Limited", "WIPRO.NS", "Technology", "Information Technology Services"),
    ("divi's lab", "Divi's Laboratories Limited", "DIVISLAB.NS", "Healthcare", "Drug Manufacturers—Specialty & Generic"),
    ("bpcl", "Bharat Petroleum Corporation Limited", "BPCL.NS", "Energy", "Oil & Gas Refining & Marketing"),
    ("ioc", "Indian Oil Corporation Limited", "IOC.NS", "Energy", "Oil & Gas Refining & Marketing"),
    ("gail", "GAIL (India) Limited", "GAIL.NS", "Energy", "Utilities—Regulated Gas"),
    ("adani power", "Adani Power Limited", "ADANIPOWER.NS", "Utilities", "Utilities—Independent Power Producers"),
    ("dlf", "DLF Limited", "DLF.NS", "Real Estate", "Real Estate—Development"),
    ("trent", "Trent Limited", "TRENT.NS", "Consumer Cyclical", "Apparel Retail"),
    ("siemens", "Siemens Limited", "SIEMENS.NS", "Industrials", "Industrial Machinery"),
    ("hal", "Hindustan Aeronautics Limited", "HAL.NS", "Industrials", "Aerospace & Defense"),
    ("bel", "Bharat Electronics Limited", "BEL.NS", "Industrials", "Aerospace & Defense"),
    ("zomato", "Zomato Limited", "ZOMATO.NS", "Consumer Cyclical", "Software—Application"),
    ("paytm", "One97 Communications Limited", "PAYTM.NS", "Financial Services", "Software—Application"),
    ("jio financial", "Jio Financial Services Limited", "JIOFIN.NS", "Financial Services", "Non-Banking Financial Company"),
    ("nykaa", "FSN E-Commerce Ventures Limited", "NYKAA.NS", "Consumer Cyclical", "Internet Retail"),
    ("pb fintech", "PB Fintech Limited", "POLICYBZR.NS", "Financial Services", "Software—Application"),
    ("tata consumer", "Tata Consumer Products Limited", "TATACONSUM.NS", "Consumer Defensive", "Packaged Foods"),
    ("bajaj auto", "Bajaj Auto Limited", "BAJAJ-AUTO.NS", "Consumer Cyclical", "Auto Manufacturers"),
    ("jspl", "Jindal Steel & Power Limited", "JINDALSTEL.NS", "Basic Materials", "Steel"),
    ("jindal steel", "Jindal Steel & Power Limited", "JINDALSTEL.NS", "Basic Materials", "Steel"),
    ("indus towers", "Indus Towers Limited", "INDUSTOWER.NS", "Communication Services", "Telecom Services"),
    ("nhpc", "NHPC Limited", "NHPC.NS", "Utilities", "Utilities—Independent Power Producers"),
    ("pfc", "Power Finance Corporation Limited", "PFC.NS", "Financial Services", "Non-Banking Financial Company"),
    ("rec", "REC Limited", "RECLTD.NS", "Financial Services", "Non-Banking Financial Company"),
    ("hdfc life", "HDFC Life Insurance Company Limited", "HDFCLIFE.NS", "Financial Services", "Insurance"),
    ("sbi life", "SBI Life Insurance Company Limited", "SBILIFE.NS", "Financial Services", "Insurance"),
    ("icici pru", "ICICI Prudential Life Insurance Company Limited", "ICICIPRULI.NS", "Financial Services", "Insurance"),
    ("icici lombard", "ICICI Lombard General Insurance Company Limited", "ICICIGI.NS", "Financial Services", "Insurance"),
    ("l&t finance", "L&T Finance Holdings Limited", "LTF.NS", "Financial Services", "Non-Banking Financial Company"),
    ("godrej consumer", "Godrej Consumer Products Limited", "GODREJCP.NS", "Consumer Defensive", "Household & Personal Products"),
    ("dabur", "Dabur India Limited", "DABUR.NS", "Consumer Defensive", "Household & Personal Products"),
    ("marico", "Marico Limited", "MARICO.NS", "Consumer Defensive", "Household & Personal Products"),
    ("colgate-palmolive india", "Colgate-Palmolive (India) Limited", "COLPAL.NS", "Consumer Defensive", "Household & Personal Products"),
    ("berger paints", "Berger Paints India Limited", "BERGERPAINT.NS", "Basic Materials", "Chemicals"),
    ("pidilite", "Pidilite Industries Limited", "PIDILITIND.NS", "Basic Materials", "Specialty Chemicals"),
    ("havells", "Havells India Limited", "HAVELLS.NS", "Industrials", "Electrical Equipment"),
    ("polycab", "Polycab India Limited", "POLYCAB.NS", "Industrials", "Electrical Equipment"),
    ("srf", "SRF Limited", "SRF.NS", "Basic Materials", "Chemicals"),
    ("cummins india", "Cummins India Limited", "CUMMINSIND.NS", "Industrials", "Industrial Machinery"),
    ("ashok leyland", "Ashok Leyland Limited", "ASHOKLEY.NS", "Consumer Cyclical", "Auto Manufacturers"),
    ("united spirits", "United Spirits Limited", "MCDOWELL-N.NS", "Consumer Defensive", "Beverages—Brewers"),
    ("escorts", "Escorts Kubota Limited", "ESCORTS.NS", "Industrials", "Farm & Heavy Construction Machinery"),
    ("max financial", "Max Financial Services Limited", "MFSL.NS", "Financial Services", "Insurance"),
    ("lupin", "Lupin Limited", "LUPIN.NS", "Healthcare", "Drug Manufacturers—Specialty & Generic"),
    ("aurobindo pharma", "Aurobindo Pharma Limited", "AUROPHARMA.NS", "Healthcare", "Drug Manufacturers—Specialty & Generic"),
    ("biocon", "Biocon Limited", "BIOCON.NS", "Healthcare", "Biotechnology"),
    ("alkem", "Alkem Laboratories Limited", "ALKEM.NS", "Healthcare", "Drug Manufacturers—Specialty & Generic"),
    ("glnemark", "Glenmark Pharmaceuticals Limited", "GLENMARK.NS", "Healthcare", "Drug Manufacturers—Specialty & Generic"),
    ("gmr infra", "GMR Airports Infrastructure Limited", "GMRINFRA.NS", "Industrials", "Infrastructure Operations"),
    ("federal bank", "The Federal Bank Limited", "FEDERALBNK.NS", "Financial Services", "Private Sector Bank"),
    ("idfc first bank", "IDFC First Bank Limited", "IDFCFIRSTB.NS", "Financial Services", "Private Sector Bank"),
    ("yes bank", "YES Bank Limited", "YESBANK.NS", "Financial Services", "Private Sector Bank"),
    ("bandhan bank", "Bandhan Bank Limited", "BANDHANBNK.NS", "Financial Services", "Private Sector Bank"),
    ("oberoi realty", "Oberoi Realty Limited", "OBEROIRLTY.NS", "Real Estate", "Real Estate—Development"),
    ("macrotech", "Macrotech Developers Limited", "LODHA.NS", "Real Estate", "Real Estate—Development"),
    ("godrej properties", "Godrej Properties Limited", "GODREJPROP.NS", "Real Estate", "Real Estate—Development"),
    ("zee", "Zee Entertainment Enterprises Limited", "ZEEL.NS", "Communication Services", "Entertainment")
]
